/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab2proje1yeni;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author 180202039-180202052
 */
public class RotaFrame extends javax.swing.JFrame {
        public static int kendinesayac=0;
       
    /**
     * Creates new form RotaFrame
     */
    public RotaFrame() {
        initComponents();
        
    }

     public void paint(Graphics g) {
        
         
                Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(2f));
        
BufferedImage icon = null;
            try {
              
                icon = ImageIO.read(new File("src\\ilpixelx.png"));
            } catch (IOException ex) {
                Logger.getLogger(RotaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            if(kendinesayac==4){
                 g.drawImage(icon,0,0,1240,640,this);
                 for (int i = 0; i <Prolab2proje1yeni.yollarxy4.size(); i++) {
             g2.setColor(Color.BLACK);
       
            g2.draw(new Line2D.Double(Prolab2proje1yeni.yollarxy4.get(i).x1,Prolab2proje1yeni.yollarxy4.get(i).y1,Prolab2proje1yeni.yollarxy4.get(i).x2,Prolab2proje1yeni.yollarxy4.get(i).y2));
         }
                 System.out.println("5.Yol oluşturuldu.");
                kendinesayac=10;
            }
           else if(kendinesayac==3){
                 g.drawImage(icon,0,0,1240,640,this);
                 for (int i = 0; i <Prolab2proje1yeni.yollarxy3.size(); i++) {
             g2.setColor(Color.MAGENTA);
       
            g2.draw(new Line2D.Double(Prolab2proje1yeni.yollarxy3.get(i).x1,Prolab2proje1yeni.yollarxy3.get(i).y1,Prolab2proje1yeni.yollarxy3.get(i).x2,Prolab2proje1yeni.yollarxy3.get(i).y2));
         }
                  System.out.println("4.Yol oluşturuldu.");
                 kendinesayac++;
            }
          else  if(kendinesayac==2){
                 g.drawImage(icon,0,0,1240,640,this);
                 for (int i = 0; i <Prolab2proje1yeni.yollarxy2.size(); i++) {
             g2.setColor(Color.GREEN);
      
            g2.draw(new Line2D.Double(Prolab2proje1yeni.yollarxy2.get(i).x1,Prolab2proje1yeni.yollarxy2.get(i).y1,Prolab2proje1yeni.yollarxy2.get(i).x2,Prolab2proje1yeni.yollarxy2.get(i).y2));
         }
                 System.out.println("3.Yol oluşturuldu.");
                 kendinesayac++;
            }
          else  if(kendinesayac==1){
                 g.drawImage(icon,0,0,1240,640,this);
                 for (int i = 0; i <Prolab2proje1yeni.yollarxy1.size(); i++) {
             g2.setColor(Color.BLUE);

            g2.draw(new Line2D.Double(Prolab2proje1yeni.yollarxy1.get(i).x1,Prolab2proje1yeni.yollarxy1.get(i).y1,Prolab2proje1yeni.yollarxy1.get(i).x2,Prolab2proje1yeni.yollarxy1.get(i).y2));
         }
                  System.out.println("2.Yol oluşturuldu.");
                 kendinesayac++;
            }
          else  if(kendinesayac==0){
                 g.drawImage(icon,0,0,1240,640,this);
                 for (int i = 0; i <Prolab2proje1yeni.yollarxy.size(); i++) {
             g2.setColor(Color.RED);
    
            g2.draw(new Line2D.Double(Prolab2proje1yeni.yollarxy.get(i).x1,Prolab2proje1yeni.yollarxy.get(i).y1,Prolab2proje1yeni.yollarxy.get(i).x2,Prolab2proje1yeni.yollarxy.get(i).y2));
         }
                  System.out.println("En kısa yol oluşturuldu.");
                 kendinesayac++;
               
            }
           
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1240, 640));
        getContentPane().setLayout(null);

        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prolab2proje1yeni/ilpixelx.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1245, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param 
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RotaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RotaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RotaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RotaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RotaFrame().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
